export const FETCH_BREED_DOGS = "FETCH_BREED_DOGS";

export const FETCH_ALL_BREEDS = "FETCH_ALL_BREEDS";
export const FETCHING_BREEDS = "FETCHING_BREEDS";

export const FETCH_ALL_DOGS = "FETCH_ALL_DOGS";
export const FETCHING_DOGS = "FETCHING_DOGS";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
